name: 03 - Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on ${{ runner.os }}."
          echo "Runner OS: $RUNNER_OS"

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a Windows runner."
          # Note: $RUNNER_OS environment variable only works when shell is explicitly set to bash in windows runner
          # Unless you use the `shell: bash` option, or use `${{ runner.os }}`
          echo "Runner OS: $RUNNER_OS"
        shell: bash
