name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test

    # 1. Checkout the code from the repository
    # 2. Install dependencies of our react app
    # 3. Execute automated tests