name: 08 - Using Variables

on:
  workflow_dispatch:

env:
  GLOBAL_VAR: "I am a global/workflow env variable"
  OVERWRITTEN_VAR: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env variable"
      OVERWRITTEN_VAR: "I have been overwritten by the job env variable"
    steps:
      - name: Print Environment Variables
        env:
          STEP_VAR: "I am a step env variable"
          step_var2: "I am another step env variable"
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var2: ${{ env.step_var2 }}"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Global env var: ${{ env.GLOBAL_VAR }}"
          echo "Overwritten env var: ${{ env.OVERWRITTEN_VAR }}"

      - name: Overwrite job env variable
        env:
          OVERWRITTEN_VAR: "I have been overwritten by the step env variable"
        run: |
          echo "Overwritten env var: ${{ env.OVERWRITTEN_VAR }}"

